sudo: false

language: generic

cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work
  - $TRAVIS_BUILD_DIR/primal/.stack-work
  - $TRAVIS_BUILD_DIR/primal-memory/.stack-work
  - $TRAVIS_BUILD_DIR/primal-mutable/.stack-work
  - $TRAVIS_BUILD_DIR/primal-test/.stack-work
  timeout: 360

matrix:
  include:

  - env: GHC="8.4.4" RESOLVER="lts-12.26" STACK_YAML="stack-extra.yaml"
    os: osx

  - env: GHC="8.6.5" RESOLVER="lts-14.27" STACK_YAML="stack-extra.yaml"
    os: osx

  # Some issue with installing ghc
  # - env: GHC="8.6.5" RESOLVER="lts-15.16"
  #   os: osx

  # - env: GHC="8.8.3" RESOLVER="lts-16"
  #   os: osx


  - env: GHC="8.0.2" RESOLVER="lts-9.21" STACK_YAML="stack-extra.yaml" DISABLE_BENCHMARKS="true" DISABLE_DOCTESTS="true"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.2.2" RESOLVER="lts-11.22" STACK_YAML="stack-extra.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.4.3" RESOLVER="lts-12.14" STACK_YAML="stack-extra.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.4.4" RESOLVER="lts-12.26" STACK_YAML="stack-extra.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.6.3" RESOLVER="lts-13.9" STACK_YAML="stack-extra.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.6.4" RESOLVER="lts-13.19" STACK_YAML="stack-extra.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.6.5" RESOLVER="lts-14.27" COVERALLS_STACK_YAML="stack-extra.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.8.3" RESOLVER="lts-15.16" DISABLE_DOCTESTS="true"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: GHC="8.8.4" RESOLVER="lts-16" DISABLE_DOCTESTS="true"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: RESOLVER="nightly"
    addons: {apt: {packages: [libgmp-dev]}}

  allow_failures:
  - env: RESOLVER="nightly"

before_install:
- |
  travis_retry curl -sSL https://gist.githubusercontent.com/lehins/fd36a8cc8bf853173437b17f6b6426ad/raw/d9ddb32cac2f0dc6800be4fa54d450f0dcda6c60/git-modtime.hs -o git-modtime.hs
  travis_retry curl -sSL https://get.haskellstack.org/ | sh -s - -f
  BUILD_ARGS="--haddock --no-haddock-deps"
  if [ -z "${DISABLE_BENCHMARKS}" ]; then
     BUILD_ARGS="${BUILD_ARGS} --bench --no-run-benchmarks"
  fi
  if [ -n "${COVERALLS_STACK_YAML}" ]; then
     STACK_YAML="${COVERALLS_STACK_YAML}"
     travis_retry curl -L https://github.com/lehins/stack-hpc-coveralls/releases/download/0.0.5.0/shc.tar.gz | tar xz shc
     BUILD_ARGS="${BUILD_ARGS} --coverage"
  fi

script:
- |
  set -ex
  ARGS="--resolver $RESOLVER"
  stack $ARGS script git-modtime.hs
  # ^ ensure file modification timestamp matches the time it was committed.
  stack $ARGS test --no-run-tests $BUILD_ARGS
  # ^ ensure everything else beside test suite gets built as well.
  stack $ARGS test primal-test:memory-tests-O0 primal-test:memory-tests-O1 $BUILD_ARGS
  # stack $ARGS test primal-test:mutable-tests-O0 primal-test:mutable-tests-O1 $BUILD_ARGS
  if [ -n "${COVERALLS_STACK_YAML}" ]; then
     stack $ARGS hpc report --all
     STACK_YAML="${COVERALLS_STACK_YAML}" ./shc --partial-coverage --fetch-coverage combined custom
  fi
  if [ -z "${DISABLE_DOCTESTS}" ]; then
    stack $ARGS test primal:doctests $BUILD_ARGS
    stack $ARGS test primal-memory:doctests $BUILD_ARGS
  fi
  set -ex
